# Generated by Django 5.1.1 on 2024-10-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('task_description', models.CharField(max_length=100)),
                ('is_Completed', models.BooleanField(default=False)),
                ('assign_date', models.DateTimeField()),
            ],
        ),
    ]
