# Generated by Django 5.1.1 on 2024-10-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task_description',
            field=models.CharField(max_length=400),
        ),
    ]
