# Generated by Django 5.1.1 on 2024-10-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_taskmodel_category_taskmodel_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='assign_date',
            field=models.DateField(),
        ),
    ]
